# Update translations when the english master changes

update-po:
	msgmerge -U Slovak/strings.po English/strings.po
	msgmerge -U 'English (US)/strings.po' English/strings.po
	msgmerge -U Galician/strings.po English/strings.po
	msgmerge -U Hebrew/strings.po English/strings.po
	msgmerge -U Norwegian/strings.po English/strings.po
	msgmerge -U German/strings.po English/strings.po
	msgmerge -U Dutch/strings.po English/strings.po
	msgmerge -U Romanian/strings.po English/strings.po
	msgmerge -U Croatian/strings.po English/strings.po
	msgmerge -U Hungarian/strings.po English/strings.po
	msgmerge -U Czech/strings.po English/strings.po
	msgmerge -U Swedish/strings.po English/strings.po
	msgmerge -U Spanish/strings.po English/strings.po
	msgmerge -U Italian/strings.po English/strings.po
